name: Generate webpage content

on:
  workflow_dispatch:
  push:
    paths:
      - '*.json'

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.groovy

      - name: Generate website
        run: groovy update.groovy > gene_database/readme.md
      - name: Generate BridgeDb Webservice config files
        run: groovy makeGDBconfig.groovy

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add gene_database/readme.md *.config
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Update formatted references'
              git push
          fi
