name: Ping WikiPathways

on:
  push:
    paths:
      - 'docs/gene_database/genes.json'

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 5 minutes  # gives this repo time to update the website
      run: sleep 5m
      shell: bash
    - name: Trigger docker release
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT_WORKFLOW_WIKIPATHWAYS_BRIDGEDB_CACHE }}
        repository: wikipathways/wikipathways-database
        event-type: bridgedb-data-update-event
        # see https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/scheduled_bridge_cache.yml#L4-L5
